name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/wakil-ai
            git pull origin main
            npm install
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
